export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';
export const DISCARD_FORM = 'DISCARD_FORM';
export const FILTER_BY_STATUS = 'FILTER_BY_STATUS';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const HANDLE_SUBMIT = 'HANDLE_SUBMIT';
